### PR TITLE
Add sharing of multi-file programs

### PR DESCRIPTION
**Pull request by ianyong**
### Description

Share links now have the following additional information in order to recreate multi-file programs:
* `isFolder` - whether Folder mode is enabled
* `files` - a compressed, encoded string of a mapping from all file paths to their file contents
* `tabs` - an array of compressed, encoded file paths
* `tabIdx` - the index of the active editor tab

Most importantly, `handleHash` was written in such a way that old share links still work correctly for backward compatibility.

Part of #2176.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Code quality improvements

### How to test

The Folder mode is not yet ready for production and is disabled programmatically. Enable Folder mode for testing by changing the condition to `false`:
https://github.com/source-academy/frontend/blob/b90a7a249be4969e6127e08eedc06900db2a78d5/src/pages/playground/Playground.tsx#L609-L622

**Check that both old and new share links work.**

### CODE REVIEW

**Comment by zhaojj2209** [comment]
Currently, all files and folders are included in the share link even if the share link is generated while folder mode is disabled. Is this the intended behaviour?

**Comment by ianyong** [comment]
> Currently, all files and folders are included in the share link even if the share link is generated while folder mode is disabled. Is this the intended behaviour?

Yes. The reason is that imports & exports are handled by js-slang, meaning that in the frontend, we do not actually know which subset of files are evaluated as part of the program. It is possible that the user is importing from another local file while in Folder mode, but then disabled Folder mode. In such cases, the program would still work as the other files are merely hidden (instead of being removed). The other reason is that by always synchronising the states that matter (editor tabs, files, etc.), the link sharing behaviour is easier to reason with.

**Comment by zhaojj2209** [comment]
> Yes. The reason is that imports & exports are handled by js-slang, meaning that in the frontend, we do not actually know which subset of files are evaluated as part of the program. It is possible that the user is importing from another local file while in Folder mode, but then disabled Folder mode. In such cases, the program would still work as the other files are merely hidden (instead of being removed). The other reason is that by always synchronising the states that matter (editor tabs, files, etc.), the link sharing behaviour is easier to reason with.

Noted on this. Perhaps it would be good to add an extra disclaimer modal when generating/accessing share links so that users can be aware of this? Listed below are some scenarios where this can potentially be an issue:

- User A creates a file `a.js` when writing code on Source 2+, and later switches back to Source 1. User A then writes some code on Source 1 (`program.js`), generates a share link for the code they have written, and sends it to User B. User B will then be able to access the contents of `a.js` when they switch to Source 2+ and enable folder mode.
- User A creates a file `a.js` when writing code on Source 2+, and later accesses a share link on Source 1 where `program.js` is the only file. Once User A switches back to Source 2+ and enables folder mode, they will find that `a.js` no longer exists, as the entire folder structure has been overwritten when accessing the share link.

**Comment by martin-henz** [comment]
> > Yes. The reason is that imports & exports are handled by js-slang, meaning that in the frontend, we do not actually know which subset of files are evaluated as part of the program. It is possible that the user is importing from another local file while in Folder mode, but then disabled Folder mode. In such cases, the program would still work as the other files are merely hidden (instead of being removed). The other reason is that by always synchronising the states that matter (editor tabs, files, etc.), the link sharing behaviour is easier to reason with.
> 
> Noted on this. Perhaps it would be good to add an extra disclaimer when generating/accessing share links so that users can be made aware of this? Listed below are some scenarios where this can potentially be an issue:
> 
> * User A creates a file `a.js` when writing code on Source 2+, and later switches back to Source 1. User A then writes some code on Source 1 (`program.js`), generates a share link for the code they have written, and sends it to User B. User B will then be able to access the contents of `a.js` when they switch to Source 2+ and enable folder mode.
> * User A creates a file `a.js` when writing code on Source 2+, and later accesses a share link on Source 1 where `program.js` is the only file. Once User A switches back to Source 2+ and enables folder mode, they will find that `a.js` no longer exists, as the entire folder structure has been overwritten when accessing the share link.
> 
> We could perhaps leave this as a future enhancement in a separate PR, given that the existing behaviour of share links is to overwrite everything anyway.

I think the second item isn't surprising. When accessing a share link, the original program (including all files) will disappear.

The first item is a bit arcane. If we can catch such cases, a warning might be good. However, we should avoid general pop-up messages to highlight the possibility of this issue to occur.

**Review by zhaojj2209 — APPROVED** [review]
LGTM!

**Pull request merged**
