### PR TITLE
Reduce code duplication, standardise styling in SICP search

### PR DESCRIPTION
**Pull request by RichDom2185**
### Description

Builds on #2706. Mainly an intermediate change (non-breaking), but simply done to:

* Reduce code duplication
* Standardise component interfaces

in order to lay the groundwork for eventual migration to a much better UI for searching using omnibox (as discussed with @sayomaki over Telegram).

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Code quality improvements

### How to test

Everything should still work with regards to SICP search.

### Checklist

- [x] I have tested this code
- [ ] I have updated the documentation

### CODE REVIEW

**Review by RichDom2185 — COMMENTED** [review]
Let us aim to merge these two PRs quickly due to the importance of this feature for upcoming exam revision.

**Review by sayomaki — COMMENTED** [review]
Good update to make use of the BlueprintJS components! However, the issue of content overflow is present, and I am still trying to see if there is a resolution for that.

As for the search buttons themselves, are they still of relevance as right now? Right now I believe it will automatically show your search results through the autocomplete when search input is provided.

**Comment by RichDom2185** [comment]
> Good update to make use of the BlueprintJS components! However, the issue of content overflow is present, and I am still trying to see if there is a resolution for that.
> 
> As for the search buttons themselves, are they still of relevance as right now? Right now I believe it will automatically show your search results through the autocomplete when search input is provided.

As discussed, this PR is simply a stepping stone to #2708. This PR only focuses on making the transition to Blueprint components (alongside some interface changes) to make the subsequent migration to use omnibox easier.

Regarding the two issues:

* Overflow: fixed in #2708 (see PR description)
* Search buttons: agreed, they are of little use in this PR, but they will be needed in #2708 to bring out the omnibox

**Review by sayomaki — APPROVED** [review]
Alright, since this PR will be superseded by #2708 anyways, we can go ahead and merge it first. Everything seems to be working well except those in the aforementioned comment.

I will comment and add feedback on the more relevant changes over there instead. Thanks!

**Pull request merged**
