### PR TITLE
Improvements to the Module System 2

### PR DESCRIPTION
**Pull request by leeyi45**
With reference to this [PR](https://github.com/source-academy/modules/pull/153) and this [PR](https://github.com/source-academy/js-slang/pull/1289)

This PR also changes the `game` module to use the context system and removes the module params object.

### CODE REVIEW

**Comment by chownces** [comment]
Hi @leeyi45, are you able to rebase this branch against the current master? There are also a few TypeScript errors failing the CI currently 😅. Thanks!

**Comment by leeyi45** [comment]
@chownces The CI is failing because it's being run against the wrong version of js-slang. I'm not too sure how to fix that.

**Comment by chownces** [comment]
i see, then let's wait for the js-slang PR to be merged first then before bumping the js-slang version here!

**Review by Cloud7050 — APPROVED** [review]

**Comment by martin-henz** [comment]
Let's aim for merging and deploying for September 29. There is a week in CS1101S when modules are not used.
Till then, let's put this in "draft" mode.

**Pull request merged**
