### PR TITLE
Module Loading Changes

### PR DESCRIPTION
**Pull request by leeyi45**
Recently `js-slang` had a PR merged. This is an accompanying PR for the frontend to accommodate those changes

### CODE REVIEW

**Review by RichDom2185 — COMMENTED** [review]
We need to wait for js-slang to be bumped on NPM before merging this, right?

**Comment by leeyi45** [comment]
> We need to wait for js-slang to be bumped on NPM before merging this, right?

If the changes that I just merged are in a newer version of js-slang then I guess?

**Comment by martin-henz** [comment]
CI fails after bumping js-slang.

**Review by RichDom2185 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
