### PR TITLE
Rename to CS1101S terms

### PR DESCRIPTION
**Pull request by NhatMinh0208**
### Description

This PR renames elements in frontend to match with [js-slang's renaming scheme.](https://github.com/source-academy/js-slang/pull/1514)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [X] Code quality improvements

### Checklist

- [x] I have tested this code
- [X] I have updated the documentation

### CODE REVIEW

**Comment by RichDom2185** [comment]
Blocked by pending NPM version bump for js-slang

**Comment by sayomaki** [comment]
I've managed to update the dependencies and any conflicts for this PR with the updated js-slang pacakge added. @NhatMinh0208 are there still more changes to be made, or is this PR ready to be reviewed and merged?

**Comment by NhatMinh0208** [comment]
Should be good to go now.

**Review by sayomaki — APPROVED** [review]
Looks good to me, thanks for the changes!

**Review by RichDom2185 — APPROVED** [review]
All the &hellip;envVisualizer&hellip; items should ideally be renamed to &rarr; &hellip;cseMachine&hellip;.

But in the interest of not blocking all the other PRs, we will merge this first. The renaming can simply be done in a subsequent PR.

LGTM, thanks!

**Comment by sayomaki** [comment]
> All the …envVisualizer… items should ideally be renamed to → …cseMachine….

I think this has already been lodged as another (open) issue, nobody seems keen to take up that for the moment I suppose
- #2680

**Pull request merged**
