### PR TITLE
CSE Machine: Implement navigation arrows to jump to the next/previous change in environment (frontend)

### PR DESCRIPTION
**Pull request by DiligentPenguinn**
### Description
This PR resolves https://github.com/source-academy/js-slang/issues/1496. These are the changes implemented on the frontend side
### Changes
- [x] Update `changepointSteps` in `context` to match js-slang
- [x] Implement navigation arrows to jump to previous/next change in environment

### CODE REVIEW

**Review by RichDom2185 — COMMENTED** [review]
Hi, thanks for working on this!

We need to bump js-slang first in this PR right? That's why it's having compile errors at the moment?

**Comment by DiligentPenguinn** [comment]
@RichDom2185 yes, this PR depends on the js-slang PR

**Review by martin-henz — APPROVED** [review]
All good!

**Review by RichDom2185 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
