### PR TITLE
Fix draw_data([])

### PR DESCRIPTION
**Pull request by ngxingyu**
### Description

Since only n - 1 lines need to be drawn, the vertical lines only need to be drawn for arrays of length > 1. Previously tried to create Array of length = -1.
Fixes source-academy/js-slang#1181

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Code quality improvements

### How to test

Running `draw_data([]);` displays array with width 0
Running `draw_data([null, null]);` displays array with vertical line between boxes.

### Checklist

- [x] I have tested this code
- [ ] I have updated the documentation

### CODE REVIEW

**Review by chownces — COMMENTED** [review]
Thanks for making the fix!

Just a minor comment: should we remove the `Rect` (vertical line below) when drawing an empty array? `draw_data([]);` @martin-henz 

Before:
image

After:
image

```
// line 53
{this.props.nodes.length >= 1 && (
  <Rect
    ...
  />
)}
```

**Comment by martin-henz** [comment]
> Thanks for making the fix!
> 
> Just a minor comment: should we remove the `Rect` (vertical line below) when drawing an empty array? `draw_data([]);` @martin-henz
> 
> Before: image
> 
> After: image
> 
> ```
> // line 53
> {this.props.nodes.length >= 1 && (
>   <Rect
>     ...
>   />
> )}
> ```

I think we should make it consistent with the Environment Visualizer. It draws a small box with nothing inside:
Screen Shot 2022-01-30 at 9 39 20 AM

**Comment by ngxingyu** [comment]
Would this be acceptable: 
`let y = []; y[1] = []; draw_data(y); draw_data([]);`
image

**Comment by martin-henz** [comment]
> Would this be acceptable: `let y = []; y[1] = []; draw_data(y); draw_data([]);` image

Yes, very nice!

**Review by martin-henz — APPROVED** [review]
Very nice!

**Pull request merged**
