### PR TITLE
Fix repl

### PR DESCRIPTION
**Pull request by thomastanck**
### Description

Fixes issue #2097 due to recent changes in NativeJS.

When evaluating editor code, we normally clear the context first to reset the state of all outputs, js-slang internals, etc. to a blank initial state, then run the editor code in the fresh context.

The problem was that the context was being fetched before it was cleared. Most likely this meant that the context that the editor code was being evaluated in was a stale, now inaccessible, context, while the repl code was being evaluated in the fresh context that does not have the results of the editor code stored within.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Code quality improvements

### How to test

Run `const x = 1;` in editor, then run `x;` in REPL.

Screenshot

### Checklist

- [x] I have tested this code
- [ ] <s>I have updated the documentation</s>

### CODE REVIEW

**Review by chownces — APPROVED** [review]
Looks good!

**Review by salty-flower — APPROVED** [review]
The `context` was retrieved ahead due to the need to check for `fullJS` chapter and was not refreshed after if-else. Yes, thanks for spotting the error - the order of statements matters so much!

**Comment by shenyih0ng** [comment]
Should we include a test case to ensure the behaviour stays the same in the future?

**Comment by martin-henz** [comment]
I'm merging this because I have a demo coming up on Wednesday and want the REPL to work. I'll create an issue that we need a regression test for the REPL.

**Comment by martin-henz** [comment]
fixes #2097

**Pull request merged**
