### PR TITLE
Add tooltip for assessments that are not fully attempted

### PR DESCRIPTION
**Pull request by josh1248**
### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Code quality improvements

Resolves https://github.com/source-academy/frontend/issues/2231 by implementing the required UI improvement:

image

### CODE REVIEW

**Comment by josh1248** [comment]
Hmm, are the snapshot fails to be expected?

**Review by RichDom2185 — COMMENTED** [review]
Thanks for working on this! Can check the tests?

**Comment by RichDom2185** [comment]
> Hmm, are the snapshot fails to be expected?. I am not too sure about how to update snapshots as required.

Yes, they are (since you changed a button to a tooltip). `yarn test --updateSnapshots` (as per the README)

**Review by RichDom2185 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
