### PR TITLE
Upgrades to Achievements UI and removal of Achievement categories

### PR DESCRIPTION
**Pull request by jonas-chow**
### Description

The achievement dashboard for staff has been revamped.
- Selecting a user in the "top bar" now also causes the achievement progress shown to be that of the selected user.
- Updating the goal progress of the user now immediately updates the UI
- Selecting user or goal can now be filtered
- Staff are now able to toggle the ability to see hidden achievements
- Achievement Views now have their background images dimmed so the white text is easily visible regardless of background
- Assessment achievements now have the assessment cover image as the background image
- Assessment achievements no longer render for staff (less clutter, but you don't get to see exactly what a student sees)

The achievement settings under achievement control also received a few minor changes.
- Prerequisites and goals can now be filtered
- It's now clearer whether an achievement has variable XP or not

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Code quality improvements

#### Staff Achievement Dashboard
Log in as a staff, and go to the achievement dashboard.
Select a user, select a goal, update a goal progress for the user.
You should see that the goal progress bar increases. 
Select another user, and you should see the goal progress bar changing.
Select the same user, and you should see the goal progress bar go back to what you gave the user.

#### Student Achievement Dashboard
Log in as a staff, and set some assessments to have been released.
Log in as a student, and go to the achievement dashboard.
You should see achievements for the released assessments, with background image that is the cover image of the assessment.

#### Achievement Control
Ensure that achievement settings still work properly (achievement's goals, prerequisites, variableXP)

### Checklist

- [x] I have tested this code
- [x] I have updated the documentation

### CODE REVIEW

**Comment by chownces** [comment]
Hi, could you branch off the current main Rook PR #1878? Also please DO NOT merge this till #1878 is merged.

**Comment by chownces** [comment]
rebased

**Comment by angelsl** [comment]
@chownces The commit you created is in the future.. LOL

**Comment by chownces** [comment]
> @chownces The commit you created is in the future.. LOL

Ohh... I just switched distros on my desktop last week, havent got to fixing the windows linux dual boot time issue haha ==

**Review by chownces — APPROVED** [review]
Thanks for the much needed changes! Will revisit the achievement categorization in the future.

**Pull request merged**
