### PR TITLE
Rename `StorySimulator` to `GameSimulator`

### LINKED ISSUE #2650: Game: simulator misnamed in frontend
Currently the simulator is called "Story Simulator".

Screenshot 2023-09-03 at 12 22 40 PM

It should be called "Game Simulator".

### PR DESCRIPTION
**Pull request by Tanush-J**
### Description

fixes #2650, I have only changed the text in AcademyNavigationBar.tsx file. I think there is also a .tsx.snap file which has a mention of "Story Simulator" I haven't changed anything there.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Code quality improvements

### Checklist

- [ ] I have tested this code
- [ ] I have updated the documentation

### CODE REVIEW

**Comment by sayomaki** [comment]
Hi @Tanush-J, welcome and thanks for contributing to Source Academy! Before we can proceed, there are a few things that I think needs to be addressed first. 

Firstly, the `tsx.snap` file you have mentioned is actually generated to ensure proper code testing and consistency, and since you have edited the source code that will affect how the button will be rendered, you will also need to update the snapshots accordingly (do read the [main page section on testing](https://github.com/source-academy/frontend#testing) if you haven't done so). The snapshot file will be updated accordingly and you will need to commit that as well.

Also, have you ensured that your code passes formatting with `yarn run format` (if you have already done so, that's great!), and that no issues are introduced by your code changes when running `yarn run test`. More information can be found on the [main page under development here](https://github.com/source-academy/frontend#running-the-tests). Testing and running your code locally to ensure it works intended will really help with the review process! 

Secondly, have you considered about other parts which may have the `storySimulator` name, such as the URL route in the lines above your change,  or the `StorySimulator`-related files under `src/pages/academy/storySimulator`? Do you have any plans to address them? It's alright if you don't intend to resolve them in this PR, thanks for the contribution once again!

**Comment by Tanush-J** [comment]
Ok, I will update the .tsx.snap file and I will try to work on other parts that contain Story Simulator name

**Comment by martin-henz** [comment]
> Ok, I will update the .tsx.snap file and I will try to work on other parts that contain Story Simulator name

Great. @Tanush-J can you make an issue on this so that we can merge this PR?

Here is the suggestion to be included in the issue. In the meantime we'll merge this PR.

_**Secondly, have you considered about other parts which may have the storySimulator name, such as the URL route in the lines above your change, or the StorySimulator-related files under src/pages/academy/storySimulator? Do you have any plans to address them? It's alright if you don't intend to resolve them in this PR, thanks for the contribution once again!**_

**Review by martin-henz — APPROVED** [review]
Discussion is conclusive: this should be merged, hopefully with an Issue for a follow-up PR.

**Comment by RichDom2185** [comment]
> > Ok, I will update the .tsx.snap file and I will try to work on other parts that contain Story Simulator name
> 
> Great. @Tanush-J can you make an issue on this so that we can merge this PR?
> 
> Here is the suggestion to be included in the issue. In the meantime we'll merge this PR.
> 
> _**Secondly, have you considered about other parts which may have the storySimulator name, such as the URL route in the lines above your change, or the StorySimulator-related files under src/pages/academy/storySimulator? Do you have any plans to address them? It's alright if you don't intend to resolve them in this PR, thanks for the contribution once again!**_

I will make this issue.

**Pull request merged**
