### PR TITLE
Upgrade to Blueprint v5

### PR DESCRIPTION
**Pull request by RichDom2185**
### Description

Upgrades the version of BlueprintJS and related dependencies to v5 to future-proof the platform.

* Supersedes #2735 
* Supersedes #2736 
* Supersedes #2737 
* Supersedes #2767 
* Supersedes #2768 

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Code quality improvements

### How to test

All components work and look correct.

### Checklist

- [x] I have tested this code
- [ ] I have updated the documentation

### CODE REVIEW

**Comment by chownces** [comment]
> Despite no more compile errors, there are still some UI regressions, thus I'm keeping this PR as draft for now.

Do you recall what are the UI regressions here?

**Comment by RichDom2185** [comment]
> > Despite no more compile errors, there are still some UI regressions, thus I'm keeping this PR as draft for now.
> 
> Do you recall what are the UI regressions here?

Yes, some tables/styles look wrong. I believe they might be because of conflicts with our custom stylesheets, but I have yet to look into them in more detail.

Though notably, the date/time picker component has been revamped in v5, so the UX there suffered a lot too (though I believe functionality still works).

**Review by RichDom2185 — COMMENTED** [review]
I'm of the opinion that we should merge this ASAP so that the CP3108 frontend teams can test and perhaps report bugs in the styles (if any) before it's actually deployed for the next semester.

Thoughts? @chownces @sayomaki

**Review by sayomaki — APPROVED** [review]
LGTM so far, thanks! Let's approve and merge this, so that users are able to test the interface and look out for any missed regressions.

**Pull request merged**
