### PR TITLE
Llm rating

### PR DESCRIPTION
**Pull request by clementlemon02**
### Description

Add Star Rating Feature to LLM

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Code quality improvements

### Checklist

- [ ] I have tested this code
- [ ] I have updated the documentation

### CODE REVIEW

**Comment by martin-henz** [comment]
Conflicts need resolving. We dont have an MVP in place yet for this, so this is a bit "ahead of its time".

**Review by RichDom2185 — COMMENTED** [review]
This PR seems to be branching off the previour PR (#2554). I will redirect this PR to prevent confusion

**Comment by RichDom2185** [comment]
> This PR seems to be branching off the previour PR (#2554). I will redirect this PR to prevent confusion

Seems like I can't redirect as the previous PR is based off a fork. Will need to merge that PR first.

**Comment by RichDom2185** [comment]
> > This PR seems to be branching off the previour PR (#2554). I will redirect this PR to prevent confusion
> 
> Seems like I can't redirect as the previous PR is based off a fork. Will need to merge that PR first.

Superseded by #2659 following the rebase.

**Pull request closed without merging**
