### PR TITLE
Refactor frontend part 7

### PR DESCRIPTION
**Pull request by RichDom2185**
### Description

Supersedes #2518.

Refactors a bunch of files, most notably chat completion logic with the SICP chatbot (and chatbox UI state and rendering logic) underwent a major refactoring to reduce coupling and fix some bugs.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Code quality improvements

### Checklist

- [x] I have tested this code
- [ ] I have updated the documentation

### CODE REVIEW

**Comment by RichDom2185** [comment]
More important/relevant commits:

### https://github.com/source-academy/frontend/pull/2846/commits/85f914a0d8289c018e835c52c78016f691b5e506 Refactoring of chat completion prompt logic

telegram-cloud-photo-size-5-6111896723619169997-x


### https://github.com/source-academy/frontend/pull/2846/commits/b8cf72b65fe3eac92ddaf5994d3cd3f566c2a207 Refactoring of chat box component state & logic

telegram-cloud-photo-size-5-6111896723619169999-y

### https://github.com/source-academy/frontend/pull/2846/commits/cc0052f6cfe3d0485b1f10e2bcd21f326a14956e Decoupling of chat box UI rendering from completion logic

telegram-cloud-photo-size-5-6111896723619170001-y

**Comment by yiwen101** [comment]
@RichDom2185 
Thank you for the wonderful effort. 
LGTM.

**Review by yiwen101 — APPROVED** [review]

**Review by RichDom2185 — COMMENTED** [review]
Looked through the changes one more time and LGTM!

**Comment by RichDom2185** [comment]
> @RichDom2185 Thank you for the wonderful effort. LGTM.

Thanks for helping to catch the double request bug and suggestions!

**Pull request merged**
